version: '3.8'

services:
  towncrier-reporter:
    build: 
      context: ./reporter
    environment:
      X_BEARER_TOKEN: AAAAAAAAAAAAAAAAAAAAAOP1xgEAAAAAxN2f23XQ7aIGdmcfNTyxyNbkUmw%3DcOeCVsuDahlA0Dq9LI54i5Ox3to7stwggnTRlRvRN3G0uYQ8R8R8
      X_USERNAMES: IranInt,bbcpersian
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: x_topic
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image:  confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]


