version: '3.8'

services:
  towncrier-publisher:
      build: 
        context: ./publisher
      environment:
        KAFKA_BROKER: kafka:9092
        KAFKA_TOPIC: x_topic
        # REDIS_ADDR: redis:6379
        # REDIS_PASSWORD: password
        TELEGRAM_API_URL: https://api.telegram.org
        TELEGRAM_BOT_TOKEN: 7774689905:AAEcmR_WZ6sFkxVULVN5laZ-_IU2J6Xl-ao
      depends_on:
        - towncrier-reporter
  towncrier-reporter:
    build: 
      context: ./reporter
    environment:
      X_BEARER_TOKEN: AAAAAAAAAAAAAAAAAAAAAOP1xgEAAAAAArjOtPEDZF%2F1HRyoyCQFP5MMlw4%3Dbfh3egA3t7tVs8KkVJpJn5swLY1T0C8vLvExydi5n9ETRNLEYR
      X_USERNAMES: IranIntl,bbcpersian
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: x_topic
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: password


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image:  confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "password"]


